"""empty message

Revision ID: 191bb782f2c1
Revises: 
Create Date: 2022-05-15 20:36:34.987920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191bb782f2c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Classification', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Legs', sa.Boolean(), nullable=False),
    sa.Column('Tail', sa.Boolean(), nullable=False),
    sa.Column('Wings', sa.Boolean(), nullable=False),
    sa.Column('Flippers', sa.Boolean(), nullable=False),
    sa.Column('Size', sa.VARCHAR(length=2), nullable=False),
    sa.Column('Climate', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Endangered', sa.VARCHAR(length=50), nullable=False),
    sa.Column('Image', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    # ### end Alembic commands ###
