"""empty message

Revision ID: ceaad45088f9
Revises: f7f5c536237c
Create Date: 2022-05-22 09:44:38.505146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceaad45088f9'
down_revision = 'f7f5c536237c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'Image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('Image', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
